# Generated by Django 5.0.2 on 2025-06-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('headline', models.TextField()),
                ('summary', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('education_level', models.CharField(max_length=100)),
                ('skills_count', models.IntegerField()),
                ('connections_count', models.IntegerField()),
                ('posts_per_month', models.IntegerField()),
                ('recommendations_received', models.IntegerField()),
                ('volunteer_experience', models.BooleanField(default=False)),
                ('certifications_count', models.IntegerField()),
                ('languages_count', models.IntegerField()),
                ('profile_completeness_score', models.FloatField(default=0)),
                ('engagement_score', models.FloatField(default=0)),
                ('professional_score', models.FloatField(default=0)),
                ('network_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
